sudo: false
language: go
go:
  - master
services:
  - mongodb
  - docker
before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
install:
  - dep ensure
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker build -t
jobs:
  include:
    - stage: test
      script: go test -race -coverprofile=coverage.txt -covermode=atomic
    - stage: deploy
      script:
        - docker build -t enteam/enbase:$TRAVIS_BUILD_ID .
        - if [[ "$TRAVIS_BRANCH" == "master" ]]; then docker tag enteam/enbase:$TRAVIS_BUILD_ID enteam/enbase; fi
        - docker push enteam/enbase
        - if [[ "$TRAVIS_BRANCH" == "master" ]]; then docker push enteam/enbase; fi
      if: type = push AND repo = enteam/enbase