version: '3'
services:
  rabbit:
    image: "rabbitmq:3-management"
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - enbase
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    networks:
      - enbase
  enbase:
    image: enteam/enbase
    environment:
      - MONGO=mongo:27017
      - RABBIT=amqp://guest:guest@rabbit:5672/
    ports:
      - 1323:1323
    networks:
      - enbase

volumes:
  rabbit-data:
  mongo-data:

networks:
  enbase:
    driver: overlay