replicaCount: 1
image:
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 1323

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - chart-example.local
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

mongo: localhost:27017
rabbit: amqp://localhost:5672
