apiVersion: v1
entries:
  enbase:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-12-12T20:13:57.4695779+01:00
    description: A Helm chart for Enbase
    digest: 50e6923793bc52763bbb9338dd0c97d80a6f3c2ccceea60db6160b88c1bffd6b
    name: enbase
    urls:
    - https://raw.githubusercontent.com/enteam/enbase/master/charts/enbase-0.1.0.tgz
    version: 0.1.0
generated: 2018-12-12T20:13:57.4675789+01:00
